parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
env:
  browser: true
  node: true
plugins:
  - flowtype
  - import
  - jsx-a11y
  - react
  - react-hooks
rules:
  semi: off
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-filename-extension:
    - warn
    - extensions:
      - .js
  import/no-unresolved:
    - error
    - ignore:
        - ^diagrams/
settings:
  react:
    version: detect
